openapi: 3.0.3
info:
  title: GRUPO 1 - DOCUMENTACIÓN DE APIS
  description: |-
    Presentamos el manual de uso de nuestras apis que comprenden las entidades: Arboles y Arboles Foto.
    ### Grupo Conformado por:
    
    * Quiroz Garcia Cristian
    * Chung Mesones Carlos
    * Delgado Cabrejos Hugo
    * Perez Zelada Favio
    
    

  version: 1.0.11

servers:
  - url: http://cristianquirozusat.pythonanywhere.com
tags:
  - name: Arbol

  - name: Arbol Foto
paths:
  /api_obtenerarboles:
    get:
      tags:
        - Arbol
      summary: Listar todos los arboles (Sin descripción)
      description: Se listaran todos los arboles registrados de forma descendiente por id.
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - write:pets
            - read:pets

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order

  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
        application/xml:
          schema:
            $ref: '#/components/schemas/Order'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Order'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://cristianquirozusat.pythonanywhere.com/auth
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
