swagger: "2.0"
info:
  title: GRUPO 1 - DOCUMENTACIÓN DE APIS
  description: |-
    Presentamos el manual de uso de nuestras apis que comprenden las entidades: Arboles y Arboles Foto.
    ### Grupo Conformado por:
    
    * Quiroz Garcia Cristian
    * Chung Mesones Carlos
    * Delgado Cabrejos Hugo
    * Perez Zelada Favio
    
    

  version: 1.0.12

servers:
  - url: http://cristianquirozusat.pythonanywhere.com
tags:
  - name: Árbol
  - name: Árbol Foto
paths:
  /api_obtenerarboles:
    get:
      tags:
        - Árbol
      summary: API OBTENER ARBOLES
      description: Se listaran todos los arboles registrados de forma descendiente por id.
      operationId: listarArbol
      responses:
        '1':
          description: 
          schema:
            $ref: '#/components/schemas/Arbol'
        '-1':
          description: El proceso de Listar Arboles no culminó satisfactoriamente.
  /api_obtenerarboles_desc:
    get:
      tags:
        - Árbol
      summary: API OBTENER ARBOLES DESC
      description: Se listaran todos los arboles registrados de forma descendiente por id.
      operationId: listarArboldesc
      responses:
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbol_desc'
        '-1':
          description: El proceso de Listar Arboles con descripción no culminó satisfactoriamente.
            
  /api_obtenerarbol_nom/{nom}:
    get:
      tags:
        - Árbol
      summary: API OBTENER ARBOLES NOM
      description: Se listara el árbol registrado si el nombre coincide con alguno, si se envia el parámetro con espacio se listaran todos los arboles.
      operationId: listarArbolnom
      produces:
        - application/json
      parameters:
        - name: "nom"
          in: "path"
          description: Nombre del árbol.
          required: true
      responses:
        '1':
          description:
          schema:
                $ref: '#/components/schemas/Arbol_desc'
        '-1':
          description: El proceso de Obtener Árbol por nombre no culminó satisfactoriamente.
  /api_obtenerarbol/{id}:
    get:
      tags:
        - Árbol
      summary: API OBTENER ARBOL POR ID
      description: Se listara el árbol registrado si el nombre proporcionado coincide con alguno, si se envia el parámetro con espacio se listaran todos los arboles.
      operationId: listarArbolid
      parameters:
      - name: "id"
        in: "path"
        description: "Id de Árbol a buscar"
        required: true
      responses:
        '1':
          description:
          schema:
              $ref: '#/components/schemas/Arbol'
        '0':
          description: Árbol no encontrado.
        '-1':
          description: El proceso de Obtener Árbol por id no culminó satisfactoriamente.
  /api_obtenerarbol_desc/{id}:
    get:
      tags:
        - Árbol
      summary: API OBTENER ARBOL POR ID DESC
      description: Muestra un registro de la tabla tree según su id llamando la descripción de campos referenciados mediante las llaves foráneas.
      operationId: listarArbolidDesc
      parameters:
      - name: "id"
        in: "path"
        description: "Id de Árbol a buscar"
        required: true
      responses:
        '0':
          description: Árbol no encontrado.
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbol_desc'
        '-1':
          description: El proceso de Obtener Árbol por id con descripción no culminó satisfactoriamente.
  /api_guardararbol:
    post:
      tags:
        - Árbol
      summary: API GUARDAR ARBOL
      description: Realiza un insert en la tabla trees.
      operationId: guardarArbol
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Para consumir el API es necesario ingresar los siguientes parámetros.
          required: true
          schema:
              $ref: '#/components/schemas/Arbolg'
      
      responses:
        '0':
          description: Usuario/Zona/Especie no encontrado(a).
        '1':
          description: Árbol guardado correctamente.
        '-1':
          description: El proceso de Guardar Árbol no culminó satisfactoriamente.

  /api_actualizararbol:
    post:
      tags:
        - Árbol
      summary: API MODIFICAR ARBOL
      description: Realiza un update en la tabla trees, haciendo coincidir el id.
      operationId: actualizarArbol
      parameters:
        - in: body
          name: body
          description: Para consumir el API es necesario ingresar los siguientes parámetros.
          required: true
          schema:
            $ref: '#/components/schemas/Arbola'
      responses:
        '1':
          description: Árbol modificado correctamente.
        '0':
          description: Árbol/Usuario/Zona/Especie no encontrado(a).
        '-1':
          description: El proceso de Actualizar Árbol no culminó satisfactoriamente.

  /api_eliminararbol:
    post:
      tags:
        - Árbol
      summary: API ELIMINAR ARBOL
      description: Realiza un delete en la tabla trees, haciendo coincidir el id.
      operationId: eliminarArbol
      parameters:
      - in: body
        name: body
        description: Para consumir el API es necesario ingresar los siguientes parámetros.
        required: true
        schema:
          $ref: '#/components/schemas/Arbole'
      responses:
        '1':
          description: Árbol eliminado correctamente.
        '0':
          description: Árbol no encontrado.
        '-1':
          description: El proceso de Eliminar Árbol no culminó satisfactoriamente.
            
  /api_obtenerarbolfotos:
    get:
      tags:
        - Árbol Foto
      summary: API OBTENER ARBOLES FOTOS
      description: Lista la tabla tree photos con sus determinados campos.
      operationId: listarArbolFoto
      responses:
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbolfoto'
        '-1':
          description: El proceso de Listar Arboles Foto no culminó satisfactoriamente.

  /api_obtenerarbolfotos_desc:
    get:
      tags:
        - Árbol Foto
      summary: API OBTENER ARBOLES FOTOS DESC
      description: Lista la tabla tree photos llamando la descripción de campos referenciados mediante las llaves foráneas.
      operationId: listarArbolFotoDesc
      responses:
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbolfotod'
        '-1':
          description: El proceso de Listar Arboles Foto con descripción no culminó satisfactoriamente.

  /api_obtenerarbolfoto/{id}:
    get:
      tags:
        - Árbol Foto
      summary: API OBTENER ARBOL FOTO POR ID
      description: Muestra un registro de la tabla tree photos según su id.
      operationId: listarArbolFotoId
      parameters:
      - name: "id"
        in: "path"
        description: "Id de Árbol Foto a buscar"
        required: true
      responses:
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbolfoto'
        '0':
          description: Árbol Foto no encontrado.
        '-1':
          description: El proceso de Obtener Árbol Foto por id no culminó satisfactoriamente.

  /api_obtenerarbolfoto_desc/{id}:
    get:
      tags:
        - Árbol Foto
      summary: API OBTENER ARBOL FOTO POR ID DESC
      description: Muestra un registro de la tabla tree photos según su id llamando la descripción de campos referenciados mediante las llaves foráneas.
      operationId: listarArbolFotoIdDesc
      parameters:
      - name: "id"
        in: "path"
        description: "Id de Árbol Foto a buscar"
        required: true
      responses:
        '1':
          description:
          schema:
            $ref: '#/components/schemas/Arbolfotod'
        '0':
          description: Árbol Foto no encontrado.
        '-1':
          description: El proceso de Obtener Árbol Foto por id con descripción no culminó satisfactoriamente.

  /api_guardararbolfoto:
    post:
      tags:
        - Árbol Foto
      summary: API GUARDAR ARBOL FOTO
      description: Realiza una inserción en la tabla tree photos, asignándole una imagen codificada algorítmicamente a un árbol (tree).
      operationId: guardarArbolFoto
      parameters:
      - in: body
        name: body
        description: Para consumir el API es necesario ingresar los siguientes parámetros.
        required: true
        schema:
          $ref: '#/components/schemas/Arbolfg'
      responses:
        '1':
          description: Árbol Foto registrado correctamente.
        '0':
          description: Árbol no encontrado.
        '-1':
          description: El proceso de Guardar Árbol Foto no culminó satisfactoriamente.

  /api_actualizararbolfoto:
    post:
      tags:
        - Árbol Foto
      summary: API ACTUALIZAR ARBOL FOTO
      description: Realiza una inserción en la tabla tree photos, asignándole una imagen codificada algorítmicamente a un árbol (tree).
      operationId: actualizarArbolFoto
      parameters:
      - in: body
        name: body
        description: Para consumir el API es necesario ingresar los siguientes parámetros.
        required: true
        schema:
          $ref: '#/components/schemas/Arbolfa'
      responses:
        '1':
          description: Árbol Foto actualizado correctamente.
        '0':
          description: Árbol/Árbol Foto/Ruta no encontrado(a).
        '-1':
          description: El proceso de Actualizar Árbol Foto no culminó satisfactoriamente.

            
  /api_eliminararbolfoto:
    post:
      tags:
        - Árbol Foto
      summary: API ELIMINAR ARBOL FOTO
      description: Realiza un delete en la tabla tree photos, haciendo coincidir el id. Además elimina la imagen asociada al arbol foto.
      operationId: eliminarArbolFoto
      parameters:
      - in: body
        name: body
        description: Para consumir el API es necesario ingresar los siguientes parámetros.
        required: true
        schema:
          $ref: '#/components/schemas/Arbolfe'
      responses:
        '1':
          description: Árbol Foto eliminado correctamente correctamente.
        '0':
          description: Árbol Foto no encontrado.
        '-1':
          description: El proceso de Eliminar Árbol Foto no culminó satisfactoriamente.

components:
  schemas:
    Arbol:
      type: object
      properties:
        birth_date:
          example: '2022-06-01 00:00:00'
        created_at:
          example: '2022-06-01 00:00:00'
        description:
          example: 'null'
        id:
          example: 1
        latitude:
          example: -6.803033899479622
        longitude:
          example: -79.84077392268448
        name:
          example: 'Árbol 01'
        planting_date:
          example: '2022-07-04 00:00:00'
        specie_id:
          example: 9  
        updated_at:
          example: '2022-07-05 08:35:37' 
        user_id:
          example: 1
        zone_id:
          example: 3
    Arbolfoto:
      type: object
      properties:
        created_at:
          example: '2022-12-01 17:19:20'
        id:
          example: 70
        tree_id:
          example: 3
        updated_at:
          example: '2022-07-05 08:35:37' 
        url:
          example: 'mysite/public/files/trees/3/TpMGl5A7xNYc-2022-12-01.jpg'
    Arbolfotod:
      type: object
      properties:
        created_at:
          example: '2022-12-01 17:19:20'
        descripcion:
          example: 'Árbol 03'
        id:
          example: 70
        tree_id:
          example: 3
        updated_at:
          example: '2022-07-05 08:35:37' 
        url:
          example: 'mysite/public/files/trees/3/TpMGl5A7xNYc-2022-12-01.jpg'
    Arbol_guardar:
      type: object
      properties:
        name:
          example: 'Árbol 09'
        birth_date:
          example: '2022-06-01 00:00:00'
        planting_date:
          example: '2022-07-04 00:00:00'
        description:
          example: 'null'
        latitude:
          example: -6.803033899479622
        longitude:
          example: -79.84077392268448
        specie_id:
          example: 9 
        zone_id:
          example: 3 
        user_id:
          example: 1
    Arbole:
      type: object
      properties:
        id:
          example: 9
    Arbolfg:
      type: object
      properties:
        imagen:
          example: Aqui se inserta la imagen codificada en b64
        tree_id:
          example: 3
    Arbolfa:
      type: object
      properties:
        id:
          example: 68
        url:
          example: 'mysite/public/files/trees/3/TpMGl5A7xNYc-2022-12-01.jpg'
        tree_id:
          example: 3
    Arbolfe:
      type: object
      properties:
        id:
          example: 68
    Arbol_desc:
      type: object
      properties:
        birth_date:
          example: '2022-06-01 00:00:00'
        created_at:
          example: '2022-06-01 00:00:00'
        description:
          example: 'null'
        especie:
          example: 'Pistacia lentiscus'
        familia_id:
          example: 9
        familia_nombre:
          example: 'Cupresáceas'
        id:
          example: 9
        latitude:
          example: -6.803033899479622
        longitude:
          example: -79.84077392268448
        name:
          example: 'Árbol 09'
        planting_date:
          example: '2022-07-04 00:00:00'
        specie_id:
          example: 9  
        updated_at:
          example: '2022-07-05 08:35:37' 
        user_id:
          example: 1
        usuario:
          example: 'Pablito Admin'
        zona:
          example: 'Zona 3'
        zone_id:
          example: 3     
    Arbolg:
      type: object
      properties:
        name:
          example: 'Árbol 09'
        birth_date:
          example: '2022-06-01 00:00:00'
        planting_date:
          example: '2022-07-04 00:00:00'
        description:
          example: 'Arbol importado'
        latitude:
          example: -6.803033899479622
        longitude:
          example: -79.84077392268448
        specie_id:
          example: 9 
        zone_id:
          example: 3 
        user_id:
          example: 1
    Arbola:
      type: object
      properties:
        id:
          example: 9
        name:
          example: 'Árbol 09'
        birth_date:
          example: '2022-06-01 00:00:00'
        planting_date:
          example: '2022-07-04 00:00:00'
        description:
          example: 'Arbol importado'
        latitude:
          example: -6.803033899479622
        longitude:
          example: -79.84077392268448
        specie_id:
          example: 9 
        zone_id:
          example: 3 
        user_id:
          example: 1
